apiVersion: v1
kind: ConfigMap
metadata:
  name: gaiad-config
data:
  config: |
    {{ tpl (.Files.Get "config/config.toml") . | nindent 4 }}
  client: |
    {{ tpl (.Files.Get "config/client.toml") . | nindent 4 }}
  app: |
    {{ tpl (.Files.Get "config/app.toml") . | nindent 4 }}
  genesis: |
    {{ .Files.Get "config/genesis.json" | nindent 4 }}
