apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  name: gaid
  labels:
    app: gaid
spec:
  type: NodePort
  ports:
  - port: 26656 
    targetPort: 26656
    nodePort: 26656
  selector:
    app: gaid
