# Default values for gaia_deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image: "oplakida/gaia:v17.2.0"
cmd: "start"
resources:
  limits:
    memory: 4Gi
  requests:
    memory: 4Gi

# Gaiad config
minimumGasPrices: "0.025uatom"
chainId: "cosmoshub-4"
moniker: "dazzling_shtern"
prometheus: true
